# Generated by Django 2.2.3 on 2019-07-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conquista', models.CharField(max_length=50)),
                ('valor', models.IntegerField(default=0)),
                ('disponivel', models.BooleanField(default=False)),
                ('conteudo', models.FileField(upload_to='conquista/')),
            ],
        ),
    ]
